### ISSUE TITLE
Can you create a video explaining how to use it and post it on YouTube？

### ISSUE THREAD

**Issue by qq912150317** [livekit/sip#32]
I have read the document, but still don't understand how to use it. I hope you can provide a video explanation of the usage process. Thank you very much。

**Comment by Sean-Der** [comment]
Hi @qq912150317 

What aren’t you able to use? Were you able to build and deploy it? Does the test client work?

**Comment by qq912150317** [comment]
Thank you very much for your answer. There is no problem with building and deploying. I used APIs to create SIP Trunk and SIP Dispatch Rules. I tried using freeswitch and MicroSIP for testing, but both failed to register
![20231222085338](https://github.com/livekit/sip/assets/110219509/96b2e4e0-962b-4d1b-8da0-3b1ecca5b7ac)

**Comment by Sean-Der** [comment]
Sorry we don’t support Register, only Invite. 

Do you have a workflow that you want an extension available from LiveKit?

**Comment by qq912150317** [comment]
Thank you very much. I hope to be able to link to livekit sip through freeswitch sip, with the client using jssip. Is this okay?

**Comment by dennwc** [comment]
For now we are mostly focused on supporting SIP Trunk Providers, so we only support features that they require. It will take some time to support the rest of SIP protocol.

You mentioned JSSIP, so maybe you can use [LiveKit JS SDK](https://docs.livekit.io/realtime/quickstarts/javascript/) directly instead of going through SIP? Just want to understand your workflow better.

**Comment by qq912150317** [comment]
Thank you very much, it's very useful
