### ISSUE TITLE
No SIP Trunk or Dispatch Rules matched.But have it

### ISSUE THREAD

**Issue by qq912150317** [livekit/sip#38]
![image](https://github.com/livekit/sip/assets/110219509/bd0bc1ac-28c2-46ed-9f33-b70b057dac06)
![image](https://github.com/livekit/sip/assets/110219509/5e15ed6f-ec16-4a9a-a5dc-4a32fac47c7a)
![1a3a35859ff9f7a4868eae9879500e0](https://github.com/livekit/sip/assets/110219509/58f5922a-ed62-443d-a5fc-2e188839331f)

**Comment by dennwc** [comment]
Hi! I think there are two issues here.

First, you set `"inbound_number_regexp": "5555551212"`, but I see in logs that the caller identifies itself as `"not-used"`. You either can remove regexp (`"inbound_number_regexp": []`), or match you caller string (`"inbound_number_regexp": "not-used"`).

The second reason is that the Trunk must have a correct number in `outbound_number`, so that it matches the destination number for inbound calls. In you case, it should be `"outbound_number": "15555551212"`.

Both issues must be addressed, otherwise the Trunk won't match.

Let me know if it helps!

**Comment by qq912150317** [comment]
Thank you very much, it's very useful
